// Generate random number from 1 to 100
// Get a number from user
// create a counter, which starts from 0 upto 10
//To check whether user provided number is equal to random num generated by computer
// 

const myButton = document.getElementById("btn_guess");

var guess,_userPrevNum;
var _previousGuess = [];
var count = 10;
var randomNumber = Math.floor(Math.random() * 100) + 1;
// console.log(randomNumber);

function getGuess(){
    guess = document.getElementById("guess_num").value;
    if (guess) {
        count--;
        _previousGuess.push(guess);
        // console.log(guess);
        // console.log(_previousGuess);
        checkNum();
    }
    // checkNum();
}

function checkNum(){
    var wrongGuessElem = document.querySelector('#prev_guess');
    wrongGuessElem.style.display = 'block';
    _userPrevNum = document.getElementsByClassName("wrongGuess")[0].getElementsByTagName("span")[0];
    _userPrevNum.textContent = "Your Guesses: " + _previousGuess.join(", ");
    var _geussCount = document.getElementById("guessCount");
    
    var _wrongAnswer = document.querySelector('#wrong');
    var _correctanswer = document.querySelector('#correct');
    var _startAgain = document.querySelector('.startAgain_btn');
    if(guess == randomNumber && count >= 0){
        _wrongAnswer.style.display = 'none';
        _correctanswer.style.display = 'block';
        console.log("Congo!! You Guessed it correctly"); 
        myButton.disabled = true;
        _startAgain.style.display = 'block'; 

    }else if(guess > randomNumber && count >= 1){
        _wrongAnswer.style.display = 'block';
        _correctanswer.style.display = 'none';
        _wrongAnswer.textContent = "Wrong Guess, Your Guess is too High";
        // console.log("Your number is High!!");
    }else if(guess < randomNumber && count >= 1){
        _wrongAnswer.style.display = 'block';
        _correctanswer.style.display = 'none';
        _wrongAnswer.textContent = "Wrong Guess, Your Guess is too Low";
        // console.log("Your number is Low!!");
    }else if(guess != randomNumber && count <= 1){
        _wrongAnswer.style.display = 'block';
        _correctanswer.style.display = 'none';
        _wrongAnswer.textContent = "Game Over!! You dont have Chances!!";
        myButton.disabled = true;
        _startAgain.style.display = 'block';
        // console.log("Game over!!");
    }else{
        console.log("Invalid!!");
    }

    _geussCount.textContent = "Total Guess remaining: " + count;
}


function returnHome(){
    window.location.href = "index.html";
}




